feedzero/feeds/urls.py
from django.urls import path

from feedzero.feeds import views


app_name = "feeds"
urlpatterns = [
    path("", views.InboxView.as_view(), name="inbox"),
    path("feeds/add/", views.FeedAddView.as_view(), name="add"),
]

feedzero/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("admin/django-rq/", include("django_rq.urls")),
    path("", include("feedzero.feeds.urls")),
    path("", include("feedzero.users.urls")),
    # TODO this probably includes too many, have a gander at it
    path("", include("django.contrib.auth.urls")),
    path("", include("social_django.urls")),
    path("api/v1/", include("feedzero.api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedzero/users/urls.py
from django.urls import include, path

from feedzero.users.views import LogoutView


app_name = "users"
urlpatterns = [
    path("logout/", LogoutView.as_view(), name="logout"),
    path("integrations/pocket/", include("feedzero.users.integrations.pocket.urls")),
]

feedzero/core/models.py
from django.db import models
from slugify import UniqueSlugify


class SlugifiedMixin(models.Model):
    """Adds a slug field to the subclassed model."""

    slug = models.SlugField(blank=True, max_length=200)

    def save(self, *args, **kwargs):
        """Override save method to populate slug field on class."""
        # TODO change slug if title changes?
        slug_attr = self.get_slug_attr()
        if not self.slug and slug_attr:
            checker = UniqueSlugify(
                unique_check=self.slug_uniqueness_check, to_lower=True, max_length=200
            )
            self.slug = checker(slug_attr, uids=self.get_initial_slug_uids())
        return super().save(*args, **kwargs)

    def get_slug_attr(self):
        """Get the attribute to use as the base for the slug.

        Defaults to title as that is most commonly used in the codebase.
        """
        return self.title

    def get_initial_slug_uids(self):
        """Populate a list of unique values for the slugify function to start from."""
        return []

    @staticmethod
    def slug_uniqueness_check(text, uids):
        """Default uniqueness check."""
        return text not in uids

    class Meta:
        abstract = True

feedzero/core/templates/components/global-nav.html
<nav class="navbar is-black is-fixed-bottom" role="navigation" aria-label="main navigation">
    <div class="container is-fluid">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'feeds:inbox' %}">
                FeedZero
            </a>

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
               data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
            </div>

            <div class="navbar-end">
                <div class="navbar-item has-dropdown has-dropdown-up is-hoverable">
                    <a class="navbar-link is-arrowless" href="/">
                        <i class="fas fa-plus"></i>
                    </a>
                    <div class="navbar-dropdown is-right">
                        <a class="navbar-item" href="{% url 'feeds:add' %}">
                            Feed
                        </a>
                        <a class="navbar-item" href="/">
                            Rule
                        </a>
                    </div>
                </div>
                <div class="navbar-item has-dropdown has-dropdown-up is-hoverable">
                    <a class="navbar-link is-arrowless" href="/">
                        <i class="fas fa-cog"></i>
                    </a>
                    <div class="navbar-dropdown is-right">
                        <a class="navbar-item" href="/">
                            My Account
                        </a>
                        <a class="navbar-item" href="/">
                            Billing
                        </a>
                        <a class="navbar-item" href="/">
                            Privacy
                        </a>
                        <a class="navbar-item" href="{% url 'users:logout' %}">
                            Logout
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>